### ISSUE TITLE
Using logger instead of Error-Stream

### ISSUE THREAD

**Issue by majuwa** [FluidTrust/Palladio-Addons-Uncertainty-VariationCreation#12]
It is probably beneficial to replace the usage of printStackTrace() with a logger call. For instance at
https://github.com/FluidTrust/Palladio-Addons-Uncertainty-VariationCreation/blob/23dfc6c890de956bdb3c9403f4fb9aab6e798278/bundles/org.palladiosimulator.pcm.uncertainty.variation.UncertaintyVariationModel.gen.pcm/src/org/palladiosimulator/pcm/uncertainty/variation/UncertaintyVariationModel/gen/pcm/UncertaintyVariationModelGenPcm.java#L56

**Comment by uybli** [comment]
Logger  Module as well as Logger Instance added to the project
