### ISSUE TITLE
Externalize String

### ISSUE THREAD

**Issue by majuwa** [FluidTrust/Palladio-Addons-Uncertainty-VariationCreation#14]
It might be a good idea to externalize the String and provide possibility to set it from the outside for instance with constructor and a default constructor.
https://github.com/FluidTrust/Palladio-Addons-Uncertainty-VariationCreation/blob/23dfc6c890de956bdb3c9403f4fb9aab6e798278/bundles/org.palladiosimulator.pcm.uncertainty.variation.UncertaintyVariationModel.gen.pcm/src/org/palladiosimulator/pcm/uncertainty/variation/UncertaintyVariationModel/gen/pcm/ScenarioManager.java#L53
The same applies to other classes with similar behaviour

**Comment by uybli** [comment]
added addition constructor which allow the setting of the different directory names (source, result, variant). Result describes the common path for all generated variants and variant replace the fixed configuration prefix.
