### ISSUE TITLE
Remove hardcoding of uncertainty model

### ISSUE THREAD

**Issue by majuwa** [FluidTrust/Palladio-Addons-Uncertainty-VariationCreation#17]
While it is ok to assume that certain models are in certain folders. The uncertainty model should be configurable. Please at least remove the definition of the string outside of actual variation creation. Use either a parameter as for the base url or define a launchconfig. Using a launchconfig would partially solve  #15 
https://github.com/FluidTrust/Palladio-Addons-Uncertainty-VariationCreation/blob/06fae49d2a65f598ea18678c8143209abc359c73/bundles/org.palladiosimulator.pcm.uncertainty.variation.UncertaintyVariationModel.gen.pcm/src/org/palladiosimulator/pcm/uncertainty/variation/UncertaintyVariationModel/gen/pcm/UncertaintyVariationModelGenPcm.java#L40

**Comment by majuwa** [comment]
a even better solution might be to deduce the base url from the url to the variationmodel

**Comment by uybli** [comment]
Base url is now computed from the url of the variation model
