### ISSUE TITLE
Check if folder Scenario exists and create it or fail gracefully

### ISSUE THREAD

**Issue by majuwa** [FluidTrust/Palladio-Addons-Uncertainty-VariationCreation#18]
https://github.com/FluidTrust/Palladio-Addons-Uncertainty-VariationCreation/blob/06fae49d2a65f598ea18678c8143209abc359c73/bundles/org.palladiosimulator.pcm.uncertainty.variation.UncertaintyVariationModel.gen.pcm/src/org/palladiosimulator/pcm/uncertainty/variation/UncertaintyVariationModel/gen/pcm/ScenarioManager.java#L39

**Comment by uybli** [comment]
changed to trying creating scenario directory if it is missing. if this fails an exception will be thrown.
